# Generated by Django 5.2.5 on 2025-08-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studentorg.basemodel')),
                ('name', models.CharField(max_length=150)),
            ],
            bases=('studentorg.basemodel',),
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studentorg.basemodel')),
                ('name', models.CharField(max_length=150)),
            ],
            bases=('studentorg.basemodel',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studentorg.basemodel')),
                ('Title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50)),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.category')),
                ('task_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.priority')),
            ],
            bases=('studentorg.basemodel',),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studentorg.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.task')),
            ],
            bases=('studentorg.basemodel',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studentorg.basemodel')),
                ('content', models.TextField()),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentorg.task')),
            ],
            bases=('studentorg.basemodel',),
        ),
    ]
